### PR TITLE
Initial commit of Confidential Computing with SLE Base Container Images using the IBM Hyper Protect Platform

### PR DESCRIPTION
**Pull request by mfriesenegger**
@chabowski and @tlssuse, please review this guide submission for publication to SUSE Technical Reference Documentation.

### CODE REVIEW

**Comment by chabowski** [comment]
> @chabowski Is there is an indent option for the lines that begin with `where`?

@mfriesenegger Hi Mike, do you refer to those lines that have numbers before the 'where' ?? I am not 100% sure if this description https://docs.asciidoctor.org/pdf-converter/latest/upgrade-to-2/#paragraph-roles-and-indent is the solution. Don't you want to keep the numbers, or go with bullet points? That would be easier.

**Comment by mfriesenegger** [comment]
> > @chabowski Is there is an indent option for the lines that begin with `where`?
> 
> @mfriesenegger Hi Mike, do you refer to those lines that have numbers before the 'where' ?? I am not 100% sure if this description https://docs.asciidoctor.org/pdf-converter/latest/upgrade-to-2/#paragraph-roles-and-indent is the solution. Don't you want to keep the numbers, or go with bullet points? That would be easier.

I started using callouts for the 13 occurrences.  Callouts work well but they are copied from the document which causes issues when pasting.  @tlssuse also asked that I not use callouts for occurrences with a single item.  I decided to remove all callouts because most had only a single item.

I looked the link you shared before asking you.  I thought there might be a preferred method for SUSE documentation.  I do not want line numbers before the 'where'.  I think bullets are OK but I did not want to assume this formatting is acceptable for the 'where' items.

Do you want me to add a commit to this PR with the bullets?

**Comment by mfriesenegger** [comment]
>  I think bullets are OK but I did not want to assume this formatting is acceptable for the 'where' items.

I tried adding a bullet in front of the first 'where'.  Doing this caused the NOTE to be pulled to the right to align with the tab.  If you are happy with the current formatting then I suggest we keep it versus trying to add a bullet or something else.

**Review by chabowski — COMMENTED** [review]
@mfriesenegger the document looks good to me. I will merge the PR into main now and do my edits and doc checks from there. Thank you very much!

**Review by chabowski — APPROVED** [review]

**Pull request merged**
