### PR TITLE
Quick corrections run, non-exhaustive

### PR DESCRIPTION
**Pull request by sknorr**
fixed here:
* a few typos
* ( spaces within parentheses ) -- these were fairly consistent, so they seemed intentional, but orthographically rather quirky
* ... and then I added three more commits!

---

other stuff I noticed that I may be able to take a look at later, as directed by you:

* missing periods in some cases, especially after links/footnotes
* deep nesting of lists/procedures -- in some cases that leads to half of a PDF page being taken up by indentation
* `{adoc-attributes}` not being replaced within verbatim areas (vulgo screens), not sure if those are intentional:
    ```
    ----
    curl -sfL https://get.k3s.io | \
    	INSTALL_K3S_VERSION=${K3s_VERSION} \
   	K3S_URL=https://${FIRST_SERVER_IP}:6443 \
   	K3S_TOKEN=${NODE_TOKEN} \
   	K3S_KUBECONFIG_MODE="644" \
   	sh -
   ----
    ```
* using plaintext references to other chapters rather than clickable `<<cross-refs>>`

### CODE REVIEW

**Review by bwgartner — APPROVED** [review]
good finds, thanks for these typo fixes (forgot to do recent spelling checks)

**Review by bwgartner — APPROVED** [review]
FWIW, this was a personal preference (and tried to use consistently) so that cut-n-paste of an entry in ( content ) was easy to not get the parentheses, but okay with this change/consistency

**Review by bwgartner — APPROVED** [review]
okay with this wj change/convention for footnotes

**Review by bwgartner — APPROVED** [review]
good find for en-dash/hyphen

**Comment by bwgartner** [comment]
>     * `{adoc-attributes}` not being replaced within verbatim areas (vulgo screens), not sure if those are intentional:
>       ```
>       ----
>       curl -sfL https://get.k3s.io | \
>       	INSTALL_K3S_VERSION=${K3s_VERSION} \
>       K3S_URL=https://${FIRST_SERVER_IP}:6443 \
>       K3S_TOKEN=${NODE_TOKEN} \
>       K3S_KUBECONFIG_MODE="644" \
>       sh -
>       ----
>       ```
> 

The above ${variables} are not undefined adoc_attributes, but related to the previous process lines/steps that are variables set during run-time

**Comment by bwgartner** [comment]
> fixed here:
> 
>     * a few typos
> 
>     * ( spaces within parentheses ) -- these were fairly consistent, so they seemed intentional, but orthographically rather quirky
> 
>     * ... and then I added three more commits!

So okay will all of these, feel free to commit/merge, and then the previous RI-Rancher (to adopt these changes) and the new RI-K3s sets can be published as well

**Comment by sknorr** [comment]
Thank you for the review and the helpful comments!

**Pull request merged**
