### PR TITLE
K r rc csco 1649773315

### PR DESCRIPTION
**Pull request by bwgartner**
Two included commits

f869258  - fixed section headers to not have links (addressing PDF output issues)
2a78f69 - added new RC content for Cisco

and with both completed, utilize this content to

    create new docs for 6x Cisco RCs
    republish new RCs all other RCs to docserve for review
    and once these updated doc versions are confirmed, merge this branch content into main and publish to main doc web site and this branch can then be removed

### CODE REVIEW

**Review by chabowski — COMMENTED** [review]
Hi Bryan, 
the PR looks good so far. I will merge it now. Just one comment: 
According to our policies and our Style Guide, we do not use the word "utilize" but "use" in technical documents. 
Thank you very much!

**Comment by chabowski** [comment]
@bwgartner Hi Bryan, one more comment:
All PDF versions of all six new Cisco documents are missing the subtitle on the title page - there is no "Reference Configuration : Integrated with Cisco" printed. Could that be an attribute issue? Would you mind checking? Thank you very much!

**Comment by bwgartner** [comment]
> @bwgartner Hi Bryan, one more comment: All PDF versions of all six new Cisco documents are missing the subtitle on the title page - there is no "Reference Configuration : Integrated with Cisco" printed. Could that be an attribute issue? Would you mind checking? Thank you very much!

This has been the case for quite some time, for all the RCs, in that the <title>:<subtitle>/n<prodname> is only shown on the 2nd page of the PDF output. Guessing this might be based upon the CSS/STYLEROOT being used for SBPs/TRDs

**Comment by bwgartner** [comment]
> Hi Bryan, the PR looks good so far. I will merge it now. Just one comment: According to our policies and our Style Guide, we do not use the word "utilize" but "use" in technical documents. Thank you very much!

Either you or I can do that substitution/commit (across the remaining 12 files with that word)

**Comment by chabowski** [comment]
> > Hi Bryan, the PR looks good so far. I will merge it now. Just one comment: According to our policies and our Style Guide, we do not use the word "utilize" but "use" in technical documents. Thank you very much!
> 
> Either you or I can do that substitution/commit (across the remaining 12 files with that word)

Done :-)

**Pull request merged**
