### PR TITLE
disclaimer: update wording to match new SBP disclaimer

### PR DESCRIPTION
**Pull request by sknorr**
As discussed earlier today, a wording update for the disclaimer. (The new version is not yet fully propagated on the SBP side.)

### CODE REVIEW

**Review by bwgartner — APPROVED** [review]
This update looks fine, feel free to merge and update the published content (assuming the multi-line approach vs. standard paragraph of conent renders properly)

**Comment by sknorr** [comment]
@bwgartner A little late to be asking, but the website now advertises "Technical Reference Documentation", the disclaimer uses "Technical Reference Documents" (which I did not change).

Which should be the official version?

**Comment by bwgartner** [comment]
> @bwgartner A little late to be asking, but the website now advertises "Technical Reference Documentation", the disclaimer uses "Technical Reference Documents" (which I did not change).
> 
> Which should be the official version?

Certainly can match what the website cites, so Documents -> Documentation is fine

**Comment by sknorr** [comment]
@bwgartner Thanks for the quick response! I took the liberty of just going ahead and pushing 4e06919.

**Pull request merged**
