### PR TITLE
TS jupyterlab container update

### PR DESCRIPTION
**Pull request by tlssuse**
Hi, @chabowski :

This guide has been updated for SLES 15 SP5.
I added the major version (15) to the productname and platform meta tags, but I still don't want to include the specific service packs.
There are a few changes scattered throughout the document to provide clarity or additional examples.
Also, I tried to address some formatting inconsistencies.
For example, I tried to match the style in our normal documentation for PLACEHOLDERS appearing in commands.
Don't hesitate to reach out to me if you have any questions or concerns.

And, thank you!

### CODE REVIEW

**Review by chabowski — APPROVED** [review]
Hi @tlssuse the changes look good to me. I will merge the PR and perform several checks from there. Thank you!

**Comment by chabowski** [comment]
Hi @tlssuse could you build the document locally? I am getting validation errors due to missing attributes 

```
asciidoctor: WARNING: skipping reference to missing attribute: product1_docs_baseurl
asciidoctor: WARNING: skipping reference to missing attribute: newpythonbin
```
Could you do a quick check? Thank you!

**Comment by tlssuse** [comment]
Hi, @chabowski : Yes, I rendered both PDF and HTML with no warnings.  Checking now.

**Comment by tlssuse** [comment]
Okay, I see what happened.  The DC-gs_sles_jupyterlab_container documention is the one I submitted.  It renders fine.

Some changes to the DC-gs_sles_jupyter-jupyterlab documentation got captured in the PR (I'm not sure how).

Can we roll back the changes to gs_sles_jupyter-jupyterlab.adoc and gs_sles_jupyter-jupyterlab-docinfo.xml?
If not, I can probably fix those changes manually.

**Comment by chabowski** [comment]
The merge of the PR has been reverted. You should be able now to check your branch and see what happened. 
From what I could find: 
In DC...Jupyterlab_container" you used a variable  `newpythonbin `inside the text which is not defined in the document. Probably the same issue with the other variable  `product1_docs_baseurl` - but I could not verify that yet.

**Pull request merged**
