### PR TITLE
Clastix 202409: Metadata and variables updates to CLASTIX getting started guide

### PR DESCRIPTION
**Pull request by tlssuse**
@chabowski & @janajaeger :
Please review this draft PR for the metadata updates in the CLASTIX getting started guide and provide feedback.

### CODE REVIEW

**Review by janajaeger — COMMENTED** [review]
Looks good to me, but Meike is the one with the most TRD expertise here. I am just happy to see the descriptions coming along ;)

**Review by chabowski — COMMENTED** [review]
@tlssuse Hi Terry, thanks for sharing. As far as I can see, it looks already quite good. 
However, I have the following questions or comments: 

For the SBPs for the product names, I only use the meta tag:

`<meta name="productname">
  <productname version="{comp1-version1}">{comp1-full}</productname>
</meta>`

and not at all anymore 

`<productname>{comp1-full}</productname>
<productnumber>{comp1-version1}</productnumber>`

This is to avoid any conflict by providing duplicate product names. I'd propose you'll do the same, to be on the safe side.
Also, I am currently using the <meta name="productname"> tag exclusively for SUSE products.

In addition, we need the `<meta name="platform">` tag for the PDF and HTML cover respective layout. Here we should provide ALL names of **relevant** involved products and/or technologies, means also those from third parties. Just "line up" the full product names with version numbers, if possible - one "meta name="platform"> for each product.

Does the 
`<meta name="social-desc">{description-social}</meta>`
already contain a real 55 characters description? I cannot see it from the adoc file - might just be "blinded" ;-). 

Thank you!!

**Comment by tlssuse** [comment]
Thank you both so much for the quick replies.
I will make these updates and also double-check that the {description-social} variable is defined in the -vars.adoc file.

**Comment by chabowski** [comment]
@tlssuse Hi Terry - one more thing to check is the date. In the docinfo.xml, we need the <revhistory> tag: 

`<revhistory xml:id="rh-art-sap-eic-slemicro54">
    <revision>
        <date>2024-07-15</date>
        <revdescription>
            <para> </para>
        </revdescription>
    </revision>
</revhistory>`

For that, we need every adoc do get a unique article ID. Do you by chance recall the conversation about that we had in the channel ? This article ID needs to be placed below the :docinfo and before the title of the doc. For the example above, the article ID looks as follows:

`:docinfo:
//test
// defining article ID
[#art-sap-eic-slemicro54]`

I usually try to take the doc file name as article ID - if it is too long, I try to shorten it reasonably.

In the DC file, the document date 
`# Set document date (yyyy-mm-dd)
ADOC_ATTRIBUTES+=" --attribute docdate=2023-07-24"`

should be outcommented to ensure the two date tags will not conflict.

We should check with @janajaeger and @tomschr if this information can be adjusted later, or needs to be there immediately.
@tomschr if there is no <revhistory> date, will the stylesheets take the <attribute docdate> instead?

Thank you!

**Comment by tlssuse** [comment]
@janajaeger & @chabowski :

I found the following in one of our shared notes:

> This information is needed by Jana for Google Analytics
>     <productname>productname1</productname>
>     <productnumber>12 SP4, 12 SP5, 15, ...</productnumber>
> or
>     <productname>productname1 versionnumber, productname2 versionnumber, ...</productname>

So, I would just like to double-check that
>   <productname>{comp1-full}</productname> <productnumber>{comp1-version1}</productnumber>
is no longer required and can be removed.

**Comment by chabowski** [comment]
@janajaeger do you need <productname> and <productversion> for GA? 
I think this information has become obsolete?
We need to make sure that <meta name="productname"> and the old <productname> tag do not conflict ...

**Comment by janajaeger** [comment]
> @janajaeger & @chabowski :
> 
> I found the following in one of our shared notes:
> 
> > This information is needed by Jana for Google Analytics
> > productname1
> > 12 SP4, 12 SP5, 15, ...
> > or
> > productname1 versionnumber, productname2 versionnumber, ...
> 
> So, I would just like to double-check that
> 
> > {comp1-full} {comp1-version1}
> > is no longer required and can be removed.

What I need for GA and literally cannot live without is the product name and version info the HTML's <meta name="title"> tag . So, I would advise that you build and test with and without your latest change (remove productname). If the product info shows up in the title even without the legacy "productname", then all is well. If not, we keep both for now.

**Comment by chabowski** [comment]
Hi @tlssuse - you might want to have a look at the SBP meta data branch:
https://github.com/SUSE/suse-best-practices/tree/sbp-rework-metadata-04042024

As an example, the following doc might help: 
https://github.com/SUSE/suse-best-practices/blob/sbp-rework-metadata-04042024/adoc/SAP-EIC-Main-docinfo.xml
The following contains all tags and meta tags I am using in the SPBs:

`<dm:docmanager xmlns:dm="urn:x-suse:ns:docmanager">
    <dm:bugtracker>
        <dm:url>https://github.com/SUSE/suse-best-practices/issues/new</dm:url>
        <dm:product>SAP Edge Integration Cell on SUSE</dm:product>
    </dm:bugtracker>
</dm:docmanager>



<meta name="series">Best Practices</meta>
<meta name="category">
     <phrase>SAP</phrase>
</meta>
<meta name="task">    
    <phrase>Data Intelligence</phrase>
    <phrase>Containerization</phrase>
    <phrase>Installation</phrase>
</meta>

<meta name="title">SAP Edge Integration Cell on SUSE</meta>
<meta name="description">This document describes how to make use of SUSE’s full stack offerings for container workloads for an installation of SAP's Edge Integration Cell.</meta>
<meta name="social-descr">Install SAP's EIC on SUSE’s container workloads stack</meta>
<meta name="productname">
    <productname version="5.4">SUSE Linux Enterprise Micro</productname>
    <productname version="2">Rancher Kubernetes Engine</productname>
    <productname version="2.8.3">Rancher Prime</productname>
    <productname version="1.5.5">Longhorn</productname>    
    </meta>

<meta name="platform">SUSE Linux Enterprise Micro 5.4</meta>
<meta name="platform">Rancher Kubernetes Engine 2</meta>
<meta name="platform">Longhorn</meta>
<meta name="platform">Rancher Prime</meta>
<meta name="platform">SAP Integration Suite</meta>

<authorgroup>
    <author>
        <personname>
            <firstname>Kevin</firstname>
            <surname>Klinger</surname>
        </personname>
        <affiliation>
            <jobtitle>SAP Solution Architect</jobtitle>
            <orgname>SUSE</orgname>
        </affiliation>
    </author>
    <author>
        <personname>
            <firstname>Dominik</firstname>
            <surname>Mathern</surname>
        </personname>
        <affiliation>
            <jobtitle>SAP Solution Architect</jobtitle>
            <orgname>SUSE</orgname>
        </affiliation>
    </author>
    <author>
        <personname>
            <firstname>Dr. Ulrich</firstname>
            <surname>Schairer</surname>
        </personname>
        <affiliation>
            <jobtitle>SAP Solution Architect</jobtitle>
            <orgname>SUSE</orgname>
        </affiliation>
    </author>
</authorgroup>

<cover role="logos">
    <mediaobject>
        <imageobject role="fo">
          <imagedata fileref="suse.svg" width="5em" align="center" valign="bottom"/>
        </imageobject>
        <imageobject role="html">
          <imagedata fileref="suse.svg" width="152px" align="center" valign="bottom"/>
        </imageobject>
    </mediaobject>
</cover>

<revhistory xml:id="rh-art-sap-eic-slemicro54">
    <revision>
        <date>2024-07-15</date>
        <revdescription>
            <para> </para>
        </revdescription>
    </revision>
</revhistory>`

**Comment by tlssuse** [comment]
Hi, Meike and Jana:

I have built the CLASTIX documentation with and without the
<productname>...</productname> metadata.
The results are pasted below.

~ Terry

== with <productname>...</productname>

<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"
lang="en"><head><title>SUSE Rancher Prime 2.7.3, CLASTIX Kamaji | Efficient
Multi-Tenancy with CLASTIX Kamaji and SUSE Rancher Prime</title><meta
charset="UTF-8"/><meta name="viewport" content="width=device-width,
initial-scale=1.0, user-scalable=yes"/><link rel="stylesheet"
type="text/css" href="static/css/style.css"/>
<meta name="title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and
SUSE R…"/>
<meta name="description" content="Streamline deployment and management of
multi-tenant Kubernetes landscapes with CLASTIX Kamaji and CLASTIX Kamaji"/>
<meta name="product-name" content="SUSE Rancher Prime 2.7.3, CLASTIX
Kamaji"/>
<meta name="book-title" content="Efficient Multi-Tenancy with CLASTIX
Kamaji and SUSE Rancher Prime"/>
<meta name="tracker-url" content="
https://github.com/SUSE/technical-reference-documentation/issues/new"/>
<meta name="tracker-type" content="gh"/>
<meta name="publisher" content="SUSE"/><meta property="og:title"
content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE R…"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Efficient Multi-Tenancy with CLASTIX
Kamaji and SUSE R…"/>
<meta name="twitter:description" content="Streamline deployment and
management of multi-tenant Kubern…"/>


== without <productname>...</productname>

<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"
lang="en"><head><title>Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE
Rancher Prime</title><meta charset="UTF-8"/><meta name="viewport"
content="width=device-width, initial-scale=1.0, user-scalable=yes"/><link
rel="stylesheet" type="text/css" href="static/css/style.css"/>
<meta name="title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and
SUSE R…"/>
<meta name="description" content="Streamline deployment and management of
multi-tenant Kubernetes landscapes with CLASTIX Kamaji and CLASTIX Kamaji"/>
<meta name="book-title" content="Efficient Multi-Tenancy with CLASTIX
Kamaji and SUSE Rancher Prime"/>
<meta name="tracker-url" content="
https://github.com/SUSE/technical-reference-documentation/issues/new"/>
<meta name="tracker-type" content="gh"/>
<meta name="publisher" content="SUSE"/><meta property="og:title"
content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE R…"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Efficient Multi-Tenancy with CLASTIX
Kamaji and SUSE R…"/>
<meta name="twitter:description" content="Streamline deployment and
management of multi-tenant Kubern…"/>

**Comment by janajaeger** [comment]
The "without productname" example, would that be with the new <meta name="productname"> tagging or without any kind of product name tags at all. 
If it was the latter, what would be the output for new tagging only?

**Comment by chabowski** [comment]
@janajaeger Without <productname> is without the old legacy xml tag, but with the new <meta name="productname">

**Comment by chabowski** [comment]
@tlssuse Terry, in the "without productname" output, the product names are missing
`meta name="product-name" content="SUSE Rancher Prime 2.7.3, CLASTIX Kamaji"`

Did you use the `meta name="productname"` tag here?

**Comment by chabowski** [comment]
@tlssuse So, after consultation with Jana, we'd say: keep both tags for now

**Comment by tlssuse** [comment]
> @tlssuse Terry, in the "without productname" output, the product names are missing, which are there with the `productname` `meta name="product-name" content="SUSE Rancher Prime 2.7.3, CLASTIX Kamaji"`
> 
> Did you use the `meta name="productname"` tag here?

Yes, `<meta name="productname">` is set.
The contents of this metadata tag appears merged into the HTML `<title>`.
However, it seems that the contents of the `<productname>`  tag appears in the published metadata as:
`<meta name="product-name" content="SUSE Rancher Prime 2.8.6, CLASTIX Kamaji 1.0.0"/>`


The latest version now includes all three metadata tags with essentially the same information:
`
<meta name="productname">
  <productname version="{comp1-version1}">{comp1-full}</productname>
  <productname version="{comp2-version1}">{comp2-full}</productname>
</meta>
<productname>{comp1-full} {comp1-version1}, {comp2-full} {comp2-version1}</productname>
<meta name="platform">{comp1-full} {comp1-version1}</meta>
<meta name="platform">{comp2-full} {comp2-version1}</meta>
`

This results in the following `<meta name=` output:
`
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><title>SUSE Rancher Prime 2.8.6, CLASTIX Kamaji 1.0.0 | Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE Rancher Prime</title><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"/><link rel="stylesheet" type="text/css" href="static/css/style.css"/>
<meta name="title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE R…"/>
<meta name="description" content="Streamline deployment and management of multi-tenant Kubernetes landscapes with CLASTIX Kamaji and CLASTIX Kamaji"/>
<meta name="product-name" content="SUSE Rancher Prime 2.8.6, CLASTIX Kamaji 1.0.0"/>
<meta name="book-title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE Rancher Prime"/>
<meta name="tracker-url" content="https://github.com/SUSE/technical-reference-documentation/issues/new"/>
<meta name="tracker-type" content="gh"/>
<meta name="publisher" content="SUSE"/><meta property="og:title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE R…"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Efficient Multi-Tenancy with CLASTIX Kamaji and SUSE R…"/>
<meta name="twitter:description" content="Streamline deployment and management of multi-tenant Kubern…"/
`

Also, I made a large number of updates, including refactoring the guide to newer versions of SUSE Rancher Prime and CLASTIX Kamaji.


Please take a look when you have a chance.

**Comment by janajaeger** [comment]
@tlssuse I have to start working on the TRD repo this very moment. I'll try to grab whatever metadata you added from your branch and try to derive missing ones from the document itself. We cannot afford to wait another day as all JSON needs to be ready for the final build by tomorrow morning our time.

We might end up having to work our way backwards from the JSON.  If I notice any weirdnesses coming through from the multiple productname entries during the daps metadata runs, I'll let you know.

**Comment by tlssuse** [comment]
@chabowski : PR has been marked as ready for review.

**Review by chabowski — APPROVED** [review]

**Pull request merged**
