### PR TITLE
Jupyterlab

### PR DESCRIPTION
**Pull request by tlssuse**
Hi, @chabowski : This is the document I mentioned on our call last week for hopeful publication this week.

### CODE REVIEW

**Review by chabowski — APPROVED** [review]
Hi @tlssuse - looks good to me, thanks. I will merge and do a last review/edits from there.

**Comment by chabowski** [comment]
@tlssuse question regarding the title: is this document really about SUSE Linux Enterprise or about SUSE Linux Enterprise Server?? And (starting with) which version(s) ?? Thank you!

**Comment by tlssuse** [comment]
> @tlssuse question regarding the title: is this document really about SUSE Linux Enterprise or about SUSE Linux Enterprise Server?? And (starting with) which version(s) ?? Thank you!

Hi, @chabowski : The document leverages SUSE Linux Enterprise Server 15 SP4.  I use variables to express version specific details where needed, but the document is applicable to any of the SLE 15 variants and SPs, and to openSUSE Leap 15.
If it makes sense to put "Server" in the title, I am okay with doing so.

**Comment by chabowski** [comment]
Thanks Terry - that was the reason I was asking - yes it would make sense to put Server in the title - I will do so. Thank you for the fast response!

**Pull request merged**
