### PR TITLE
doc already prepared for new TRD stylesheet

### PR DESCRIPTION
**Pull request by tlssuse**
@chabowski : This new guide is part of the Edge Analytics series and has been prepared to use the new TRD stylesheet.

### CODE REVIEW

**Review by chabowski — COMMENTED** [review]
@tlssuse looks really good! I will merge it to main and edit from there. Thank you!

**Review by chabowski — APPROVED** [review]

**Comment by chabowski** [comment]
Hi @tlssuse I have merged the document, but I have several comments: 

- Logo should be suse.svg for light backgrounds. We added it via PR to the repo, but I think the symlink needs to be adjusted?
- I have added a second platform for "SUSE Linux Enterprise Server 15 SP2" - as this doc is not only Rancher but OS is SLES. Hope this is okay.
- Do you want (me) to add the mentors to the "contributor" tag at the title page? That would work with the following tag inside `<authorgroup>` under the last `<author> `information
- -

```
    <!--<editor>
    <orgname></orgname>
    </editor>
    <othercredit>
    <orgname></orgname>
    </othercredit>-->
```
and the <editor>s are shown as "Contributors"

- Can we shorten the title and put one of the two parts in the subtitle? E.g. 
```
<title>Edge Analytics in Healthcare</title>
<subtitle>Cancer Prediction System</subtitle>
```
or vice versa?

These are just the first few comments - I will also edit the doc now

**Comment by tlssuse** [comment]
Hi, @chabowski :
Thank you for all this!

I've created a new branch "edgehealth" with some changes.

1. The suse.svg logo that I am seeing in the repo appears to be in the old SUSE brand.  I think the one we should use for light backgrounds is common/images/src/svg/suse-green-logo-green.svg and common/images/src/svg/suse-white-logo-green.svg for dark backgrounds.  I've updated the symlink and the docinfo.
2. We don't spend much time on the fact that SLES was used, but it should have mention as a platform.  Thank you for adding this.  I've updated the version to 15 SP3 and replaced my {os} variable with {platform2}.
3. We are going to skip adding the mentors and editors as contributors on the title page (though I am glad we can do that in the future).  I'd like to reserve the highlight for the student contributor.
4. I updated the docdate to 2022-12-02.
5. We have a trio of these documents that are focused on various aspects of edge analytics (in finance, healthcare, and smart cities).  It makes some sense to move "Cancer Prediction System" into a subtitle.
I found some odd behavior in trying to get the title and subtitle to render properly.  With "<title>{title}</title>" and "<subtitle>{subtitle}</subtitle>" in the docinfo file and only the "= {title}" in the adoc file, it works.  I included "= {title}: {subtitle}" in the adoc file for consistency, though.

I'll submit these changes for your review as a new PR.

**Comment by chabowski** [comment]
We are using this one - I think for the SBP repo we just renamed it to suse.svg 
SUSE_Logo-hor_L_Green-pos_sRGB

**Comment by tlssuse** [comment]
Yes, that appears to be the same logo currently coded for the document to use.
It appears the suse.svg one we have in the TRD repo is the older one.
I'll update that in another PR.

**Pull request merged**
